const MESSAGE = {
    HOMETITLE: "Home | Team Loki Tracker",
    FOOTERTITLE: "Copyright: Team Loki x To the Moon ® All Rights Reserved.",
    TEAMLOKI: "Team Loki",
    TOTHE_MOON: "To the Moon",
    LOADING_TEXT: "Loading, please wait...",
    UNEXPECTED_ERROR: "Unexpected error, please reload the page!",
    ERROR_OCCURED: "Oh well, you failed. Here some thoughts on the error that occured:",
    INVALID_CREDENTIAL: "Invalid credential. Please try again.",
    SOMETHING_WENT_WRONG: "Something went wrong!",
    NODATA_FOUND: "No Data Found.",
    PAGE_REFRESH: "Page refresh automatically within 120 seconds.",
    PRICE_BASEON: "Prices are based on",
    COINGECKO: "CoinGecko",
    CURRENT_EXCHANGERATE: "Current exchange rate",
    SIGNIN: "Sign In",
    LOGIN: "Login",
    LOGOUT: "Logout",
    INPUT_USER: "Type your username or email",
    VIEW_MANAGER_EARNING: "View Manager Earnings",
    VIEW_SPONSOR_EARNING: "View Sponsor Earnings",
    MANAGER_EARNING: "Manager Earnings",
    SPONSOR_EARNING: "Sponsor Earnings",
    MANAGER: "Manager",
    SPONSOR: "Sponsor",
    SCHOLAR: "Scholar",
    SLP: "SLP",
    AXS: "AXS",
    SLP_DESC: "Smooth Love Potion",
    TOP_MMR: "Top MMR",
    TOP_INGAME_SLP: "Top In Game SLP",
    TOP_MMR_SLP: "Top MMR and SLP",
    MMR: "MMR",
    ELO: "ELO",
    RANK: "Rank",
    LAST_CLAIMED_SLP: "Last Claimed SLP",
    LAST_CLAIMED_AT: "Last Claimed At",
    CLAIMON: "Claim On",
    ADV: "ADV",
    ADVENTURE: "Adventure",
    INGAME: "InGame",
    SHARE: "Share",
    SHARED: "Shared",
    TOTAL: "Total",
    EARNING: "Earning",
    TOTAL_EARNINGS: "Total Earnings",
    CLOSE: "Close",
    NAME: "Name",
    ARENAGAME_STATUS: "Arena Game Status",
    WIN: "Win",
    LOSE: "Lose",
    DRAW: "Draw",
    DAYS: "Day(s)"
}

export const CONSTANTS = {
    MESSAGE
}