const MESSAGE = {
    HOMETITLE: "Home | Team Loki Tracker",
    FOOTERTITLE: "Copyright: Team Loki x To the Moon ® All Rights Reserved.",
    TEAMLOKI: "Team Loki",
    TOTHE_MOON: "To the Moon",
    LOADING_TEXT: "Loading, please wait...",
    UNEXPECTED_ERROR: "Unexpected error, please reload the page!",
    ERROR_OCCURED: "Oh well, you failed. Here some thoughts on the error that occured:",
    INVALID_CREDENTIAL: "Invalid credential. Please try again.",
    SOMETHING_WENT_WRONG: "Something went wrong!",
    NODATA_FOUND: "No Data Found.",
    PAGE_REFRESH: "Page refresh automatically within 60 seconds.",
    PRICE_BASEON: "Prices are based on",
    BINANCE: "Binance",
    COINGECKO: "CoinGecko",
    CURRENT_EXCHANGERATE: "Current exchange rate",
    SIGNIN: "Sign In",
    LOGIN: "Login",
    LOGOUT: "Logout",
    INPUT_USER: "Type your username or email",
    VIEW_MANAGER_EARNING: "View Manager Earnings",
    VIEW_SPONSOR_EARNING: "View Sponsor Earnings",
    MANAGER_EARNING: "Manager Earnings",
    SPONSOR_EARNING: "Sponsor Earnings",
    MANAGER: "Manager",
    SPONSOR: "Sponsor",
    SCHOLAR: "Scholar",
    SLP: "SLP",
    AXS: "AXS",
    SLP_DESC: "Smooth Love Potion",
    TOP_MMR: "Top MMR",
    TOP_INGAME_SLP: "Top InGame SLP",
    TOP_MMR_SLP: "Top MMR and SLP",
    MMR: "MMR",
    ELO: "ELO",
    RANK: "Rank",
    RANKING: "Ranking",
    LAST_CLAIMED_SLP: "Last Claimed SLP",
    LAST_CLAIMED_AT: "Last Claimed At",
    CLAIMON: "Claim On",
    ADV: "ADV",
    ADVENTURE: "Adventure",
    INGAME: "InGame",
    SHARE: "Share",
    SHARED: "Shared",
    RONIN: "Ronin",
    TOTAL: "Total",
    EARNING: "Earning",
    EARNINGS: "Earnings",
    TOTAL_EARNINGS: "Total Earnings",
    CLOSE: "Close",
    NAME: "Name",
    ARENAGAME_STATUS: "Arena Game Status",
    WIN: "Win",
    LOSE: "Lose",
    DRAW: "Draw",
    WIN_RATE: "Win Rate",
    DAYS: "Day(s)",
    OPEN_MARKETPLACE_PROFILE: "View marketplace profile",
    OF: "of",
    ADV_QUEST_TODAY: "Adventure SLP Quest (Today)",
    INGAME_SLP: "InGame SLP",
    INGAME_SLP_SHARING: "In Game SLP Sharing",
    RONIN_PLUS_SHARING_SLP: "Ronin SLP + Sharing SLP",
    PHP_CURRENCY: "PHP Currency",
    AVERAGE: "Average",
    AVERAGE_SLP_PERDAY: "Average SLP per day",
    AVERAGE_SLP_PERDAY_V2: "Average SLP / Day",
    AVG_SLP_PERDAY: "Avg. SLP / Day",
    SHARE_SLP: "Share SLP",
    VIEW_TOTALINCOME: "View Total Income",
    TOTALINCOME: "Total Income",
    NOTIFBAR_CLICKABLE: "Notification bar is Clickable.",
    SLP_PRICE: "SLP Price",
    DATE: "Date",
    STARTED: "Started",
    TOTAL_INGAME_SLP: "Total InGame SLP",
    TOTAL_AVERAGE_SLP: "Total Average SLP",
    TOTAL_MANAGER_SLP: "Total Manager SLP",
    TOTAL_SPONSOR_SLP: "Total Sponsor SLP",
    TOTAL_SCHOLAR_SLP: "Total Scholar SLP",
    ADVENTURE_SLP: "Adventure SLP",
    SHARED_SLP: "Shared SLP",
    RONIN_SLP: "Ronin SLP",
    TOTAL_SLP: "Total SLP",
    EARNINGS_PHP: "Earnings (PHP)",
    DETAIL: "Detail",
    DETAILS: "Details",
    CATEGORY: "Category",
    VIEW_ALL_EARNINGS: "View All Earnings",
    VIEW_CURRENT_EARNINGS: "View Current Earnings",
    MANAGER_ALL_EARNINGS: "All Manager Earnings",
    MANAGER_CURRENT_EARNINGS: "Current Manager Earnings",
    MMR_RANKING: "MMR Ranking",
    TOTAL_CURRENT_EARNINGS: "Total Current Earnings",
    EMAIL_LOWMMR_SUBJECT: "Team Loki MMR Ranking",
    EMAIL_LOWMMR_MESSAGE: "You receive this automated email due to your MMR Ranking, keep it up and learn more. If need help, don't hesitate to ping on our Messenger Group Chat. Stay Low Key as our tagline.",
    EMAIL_WARNINGMMR_MESSAGE: "You receive this automated email due to your MMR Ranking, keep playing and learn more. Stay Low Key as our tagline.",
    ROI_DESCRIPTIVE: "Return of Investment",
    ROI: "ROI",
    BREED: "Breed",
    BUY: "Buy",
    INCOME: "Income",
    GUIDE_HERE: "Guides here!",
    PVP_ENERGY: "PvP Energy",
    MANAGER_SLP: "Manager SLP",
    SPONSOR_SLP: "Sponsor SLP",
    SCHOLAR_SLP: "Scholar SLP",
    EMAIL: "Email",
    DAILYSLP: "Daily SLP",
    GET: "GET",
    POST: "POST",
    EMPTY: "EMPTY",
    INSERT: "Insert",
    UPDATE: "UPDATE"
}

export const CONSTANTS = {
    MESSAGE
}